services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"
      - "4983:4983"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    command: pnpm dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
